name: test-2-a

on:
  push:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch_name:
        required: false
        type: string
        default: main

env:
  RUN_BRANCH: main

jobs:
  test-1a:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check.outputs.branch }}
    steps:
      - name: check
        id: check
        run: |
          echo ${BRANCH_NAME}
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/${REPO}/branches/${BRANCH_NAME})
          if [ "${STATUS}" -eq 200 ]; then
            echo "branch=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          else
            echo "branch=main" >> $GITHUB_OUTPUT
          fi
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ inputs.branch_name }}
          REPO: ${{ github.repository }}

  action-test-2:
    needs: test-1a
    uses: zou272937/test-action-2/.github/workflows/main.yml@main
    with: 
      branch_name: ${{ needs.test-1a.outputs.branch }}
