name: test-2

on:
  workflow_run:
    workflows: ["test-1"]
    types:
      - completed
  workflow_call:
    inputs:
      branch_name:
        required: false
        type: string
        default: main

jobs:
  test-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: test-step-2
        run: echo "Project 2" ${inputs.branch_name}
        env:
          BRANCH_RUN: ${{ inputs.branch_name }}
      - uses: actions/checkout@v4
        with:
          ref: ${BRANCH_RUN}
        env:
          BRANCH_RUN: ${{ inputs.branch_name }}
