name: test-2

on:
  workflow_run:
    workflows: ["test-1"]
    types:
      - completed
  workflow_call:
    inputs:
      branch_name:
        required: false
        type: string
        default: main

jobs:
  test-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: test-step-2
        run: echo "Project 2" ${BRANCH_RUN}
        env:
          BRANCH_RUN: ${{ github.ref_name }}
      - uses: actions/checkout@v4
        with:
          repository: zou272937/test-action-2
          ref: ${{ inputs.branch_name }}
      - name: Confirm current branch
        run: git branch --show-current
      - name: test-step-3
        run: |
          echo ${GITHUB_WORKSPACE}
          ls
