name: test-2-a

on:
  push:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch_name:
        required: false
        type: string

jobs:
  test-1a:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.find.outputs.branch }}
    steps:
      # - name: check
      #   id: check
      #   run: |
      #     echo ${BRANCH_NAME}
      #     STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/${REPO}/branches/${BRANCH_NAME})
      #     if [ "${STATUS}" -eq 200 ]; then
      #       echo "branch=${BRANCH_NAME}" >> $GITHUB_OUTPUT
      #     elif ["${BRANCH_NAME}" -eq ""]; then
      #       echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
      #     else
      #       echo "branch=main" >> $GITHUB_OUTPUT
      #     fi
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH_NAME: ${{ inputs.branch_name }}
      #     REPO: zou272937/test-action-2
      #     # REPO: ${{ github.repository }}
      - name: extract branch
        id: extra
        run: |
          BRANCH="${{ github.ref_name }}"
          echo "Branch: $BRANCH"
          ISSUE_ID=$(echo "$BRANCH" | cut -d'/' -f2)
          NAME=$(echo "$BRANCH" | cut -d'/' -f3)
          SUFFIX="${ISSUE_ID}-${NAME}"
          echo "ISSUE_ID=$ISSUE_ID" >> $GITHUB_OUTPUT
          echo "NAME=$NAME" >> $GITHUB_OUTPUT
          echo "SUFFIX=$SUFFIX" >> $GITHUB_OUTPUT

      - name: list branch
        id: list_branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/zou272937/test-action-2/branches > branches.json
          echo "Branches listed."
      - name: find matching
        id: find
        run: |
          echo "${{ steps.extra.outputs.SUFFIX }}"
          MATCH=$(jq -r --arg suffix "${{ steps.extra.outputs.SUFFIX }}" '.[] | select(.name | endswith ($suffix)) | .name' branches.json)
          if [ -z "$MATCH" ]; then
            MATCH="main"
          fi
          echo "branch=$MATCH" >> $GITHUB_OUTPUT
          echo "$MATCH"

  action-test-2:
    needs: test-1a
    uses: zou272937/test-action-2/.github/workflows/main.yml@main
    with: 
      branch_name: ${{ needs.test-1a.outputs.branch }}
